### PR TITLE
Missed a check that assumes sequential stream indices.

### PR DESCRIPTION
**Pull request by charrea6**
Not sure how it managed to work when I tested the previous change, but I'd missed this if statement. With this if statement still in, playback failed almost immediately. I can only assume that when I tested it no packets in the problem stream index where being sent.

### CODE REVIEW

**Comment by BtbN** [comment]
Could you rebase this to get rid of the merge commit?

**Comment by charrea6** [comment]
Don't think I can though I'm happy to be proved wrong!
I've tried rebasing my repo but on attempting to push the changes to github there are rejected.
Any ideas?

Out of curiosity why rebase instead of pull? I've not used the rebase command before.

**Comment by BtbN** [comment]
To keep the history clean, a merge of master just doesn't look nice.

**Comment by charrea6** [comment]
Thanks will ensure use of rebase/ffwd in future.

**Pull request closed without merging**
